name: notes
description: Notes taking app using sqflite

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  outline_material_icons: ^0.1.0
  sqflite: ^1.1.5
  intl: ^0.16.0
  url_launcher: ^5.0.3
  shared_preferences: ^0.5.3+1
  share: ^0.6.1+1
  flutter_local_notifications: 1.3.0
  flutter_duration_picker: "^1.0.0"
  esys_flutter_share: ^1.0.2
  local_auth: 0.6.2+3
  get_it: ^1.0.3+2
  path_provider: ^1.4.1
  flutter_swiper: ^1.1.4
  flutter_form_builder: ^3.0.0
  rxdart: ^0.20.0
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.5
  screenshot: ^0.1.1
  flutter_calendar_carousel: ^1.4.12
  faker: ^1.2.1
  zefyr: ^0.10.0
  device_info: ^0.4.2+4
  async: ^2.4.0
  flare_flutter: ^1.5.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.1.1
  firebase_database: ^3.0.7
  image_picker: ^0.6.3
  firebase_analytics: ^5.0.6
  googleapis: ^0.54.0
  date_utils: ^0.1.0+3
  health: ^1.0.0

    # The following adds the Cupertino Icons font to your application.   # Use with the CupertinoIcons class for iOS style icons.   cupertino_icons: ^0.1.2
  csv: ^4.0.3
  sqflite_porter:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_porter
    version: '>=0.2.0'
  simple_animations: ^1.3.11
  http: ^0.12.1
  fl_chart: ^0.8.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      -  assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: ZillaSlab
       fonts:
         - asset: fonts/ZillaSlab-Regular.ttf
         - asset: fonts/ZillaSlab-Italic.ttf
           style: italic
         - asset: fonts/ZillaSlab-Bold.ttf
           weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
