name: sorted
description: Get it done

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_porter:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_porter
    version: ">=0.2.0"
  async: ^2.4.0
  audioplayers: ^0.16.1
  auto_route: ^0.3.0
  bloc_provider: ^0.7.0
  cached_network_image: ^2.4.1
  camera: ^0.5.8+5
  cloud_firestore: ^0.13.5
  connectivity: ^0.4.9
  crop: ^0.4.1
  csv: ^4.0.3
  flutter_staggered_grid_view: ^0.3.2
  cupertino_icons: ^0.1.2
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  youtube_player_flutter: ^7.0.0+7
  date_utils: ^0.1.0+3
  device_info: ^0.4.2+4
  emoji_picker: ^0.1.0
  equatable: ^1.2.2
  esys_flutter_share: ^1.0.2
  faker: ^1.2.1
  file_picker: ^1.13.3
  firebase_analytics: ^5.0.6
  firebase_auth: ^0.16.0
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.6
  fl_chart: ^0.8.7
  flare_flutter: ^1.5.5
  flutter_bloc: ^6.0.1
  flutter_cache_store: ^0.7.2
  flutter_calendar_carousel: ^1.4.12
  flutter_duration_picker: ^1.0.0
  flutter_form_builder: ^3.0.0
  flutter_local_notifications: 1.3.0
  flutter_swiper: ^1.1.4
  scrollable_positioned_list: ^0.1.8
  get_it: ^4.0.4
  google_sign_in: ^4.1.1
  googleapis: ^0.54.0
  health: ^1.0.0
  http: ^0.12.1
  image_picker: ^0.6.3
  intl: ^0.16.0
  local_auth: 0.6.2+3
  outline_material_icons: ^0.1.0
  path_provider: ^1.4.1
  permission_handler: ^5.0.1+1
  reorderables: ^0.3.2
  rxdart: ^0.24.1
  sa_anicoto: ^1.0.3
  screenshot: ^0.1.1
  share: ^0.6.1+1
  shared_preferences: ^0.5.3+1
  simple_animations: ^1.3.11
  sqflite: ^1.1.5
  string_validator: ^0.1.4
  supercharged: ^1.10.0
  url_launcher: ^5.4.2
  zefyr: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.3.0
  build_runner: null

dependency_overrides:
  analyzer: '0.39.14'
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/notebooks/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-Regular.ttf
        - asset: fonts/ZillaSlab-Italic.ttf
          style: italic
        - asset: fonts/ZillaSlab-Bold.ttf
          weight: 700
    - family: Eastman
      fonts:
        - asset: fonts/EastmanTrial-Medium.otf
        - asset: fonts/EastmanTrial-BlackItalic.otf
          style: italic
        - asset: fonts/EastmanTrial-Bold.otf
          weight: 700
    - family: Lemonmilk
      fonts:
        - asset: fonts/LEMONMILK-Medium.otf
        - asset: fonts/LEMONMILK-MediumItalic.otf
          style: italic
        - asset: fonts/LEMONMILK-Light.otf
          weight: 200
        - asset: fonts/LEMONMILK-Bold.otf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
