name: sorted
description: Get it done

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async:
  auto_route: "2.2.0"
  bloc_provider:

  cached_network_image:
  camera:
  pin_code_fields:
  connectivity:
  crop:
  csv:
  flutter_staggered_grid_view:
  cupertino_icons:
  video_player: "2.1.5"
  confetti:
  dartz:
  data_connection_checker:
  youtube_player_flutter:
  device_info:
  emoji_picker:
  equatable:
  faker:
  scratcher:
  file_picker:
  firebase_core:
  video_trimmer:
  firebase_auth:
  firebase_crashlytics:
  cloud_firestore:
  cloud_functions:
  firebase_storage:
  firebase_messaging:
  firebase_analytics:
  flutter_ffmpeg:
  chewie:
  analyzer:
  flare_flutter:
  flutter_bloc:
  flutter_calendar_carousel:
  flutter_duration_picker:
  flutter_form_builder:
  overlay_support:
  flutter_local_notifications:
  flutter_swiper:
  scrollable_positioned_list:
  get_it:
  get:
  dio:
  google_sign_in:
  googleapis:
  health:
  http:
  image_picker:
  intl:
  local_auth:
  outline_material_icons:
  path_provider:
  permission_handler:
  reorderables:
  rxdart:
  sa_anicoto:
  screenshot:
  share:
  shared_preferences: "2.0.6"
  heat_map_calendar:
    path: packages/heat_map_calendar
  custom_calendar:
    path: packages/custom_calendar
  fl_chart:
    path: packages/fl_chart
  simple_animations:
  sqflite:
  string_validator:
  supercharged:
  url_launcher:
  zefyr:
  flutter_svg:
  material_design_icons_flutter:
  truecaller_sdk:
  pie_chart:
  firebase_dynamic_links:
  uni_links:
  razorpay_flutter:
  dart_jsonwebtoken:
  cashfree_pg:
  jitsi_meet:
  just_audio:
  audio_session:

dev_dependencies:
  auto_route_generator:
  build_runner:
  build_resolvers:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/notebooks/
    - assets/animations/
    - assets/images/onboarding/
    - assets/images/tracks/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-Regular.ttf
        - asset: fonts/ZillaSlab-Italic.ttf
          style: italic
        - asset: fonts/ZillaSlab-Bold.ttf
          weight: 700
    - family: Eastman
      fonts:
        - asset: fonts/EastmanTrial-Medium.otf
        - asset: fonts/EastmanTrial-BlackItalic.otf
          style: italic
        - asset: fonts/EastmanTrial-Bold.otf
          weight: 700
    - family: Lemonmilk
      fonts:
        - asset: fonts/LEMONMILK-Medium.otf
        - asset: fonts/LEMONMILK-MediumItalic.otf
          style: italic
        - asset: fonts/LEMONMILK-Light.otf
          weight: 200
        - asset: fonts/LEMONMILK-Bold.otf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Milliard
      fonts:
        - asset: fonts/Milliard-Medium.otf
        - asset: fonts/Milliard-Medium-Italic.otf
          style: italic
        - asset: fonts/Milliard-Light.otf
          weight: 200
        - asset: fonts/Milliard-Medium.otf
          weight: 500
        - asset: fonts/Milliard-SemiBold.otf
          weight: 600
        - asset: fonts/Milliard-Bold.otf
          weight: 700
        - asset: fonts/Milliard-ExtraBold.otf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
